[template.environment]
  GQL_HOST = "https://b.oriental-art.net/graphql"
  NUXT_IMAGE_DOMAINS = "https://b.oriental-art.net"

[build]
  command = "nuxt generate"

[images]
  remote_images = ["https://secure.woonuxt.com/.*"]
